spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-username:  risk
    data-password: risk2020
    url: jdbc:mysql://10.241.21.13:3306/riskmission?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource